{* DO NOT EDIT THIS FILE! Use an override template instead. *}

<div class="block">
    <label>{'Style'|i18n( 'design/standard/class/datatype' )}:</label>
    <select name="ContentClass_openpachildrenview_ismultiple_value_{$class_attribute.id}">
        <option value="0"
                {if not( $class_attribute.data_int1 )}selected="selected"{/if}>{'Single choice'|i18n( 'design/standard/class/datatype' )}</option>
        <option value="1"
                {if $class_attribute.data_int1}selected="selected"{/if}>{'Multiple choice'|i18n( 'design/standard/class/datatype' )}</option>
    </select>
</div>

<div class="block">
    <fieldset>
        <legend>{'Visualizzazioni'|i18n( 'design/standard/class/datatype' )}</legend>
        {if $class_attribute.content.views|count()}
            <table class="list" cellspacing="0">
                {foreach $class_attribute.content.views as $view}
                    <tr>
                        <td>
                            <label>
                            {if $view.identifier|eq('default')}
                                <input type="hidden"
                                       name="ContentClass_openpachildrenview_option_active_array_{$class_attribute.id}[{$view.id}]"
                                       value="{$view.identifier}"/>
                                <input type="checkbox" checked="checked" disabled="disabled" />
                            {else}
                                <input type="checkbox"
                                   name="ContentClass_openpachildrenview_option_active_array_{$class_attribute.id}[{$view.id}]"
                                   value="{$view.identifier}"
                                   {if $class_attribute.content.active_list|contains($view.id)}
                                       checked="checked"
                                   {/if}
                                   />
                            {/if}

                            {$view.name|wash}
                            </label>
                        </td>
                    </tr>
                {/foreach}
            </table>
        {else}
            <p>{'There are no options.'|i18n( 'design/standard/class/datatype' )}</p>
        {/if}

        {* Buttons. *}
        {if $class_attribute.content.options}
            <input class="button" type="submit"
                   name="ContentClass_openpachildrenview_activeoption_button_{$class_attribute.id}"
                   value="{'Salva visualizzazioni attive'|i18n( 'design/standard/class/datatype' )}"
                   title="{'Salva visualizzazioni'|i18n( 'design/standard/class/datatype' )}"/>
        {/if}

    </fieldset>
</div>
