{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
{let selected_id_array=$attribute.content.options
     extra_configs=$attribute.content.extra_configs}

    {* Always set the .._selected_array_.. variable, this circumvents the problem when nothing is selected. *}
    <input type="hidden" name="{$attribute_base}_openpachildrenview_selected_array_{$attribute.id}" value=""/>
    <p>
    <select id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}"
            class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
            name="{$attribute_base}_openpachildrenview_selected_array_{$attribute.id}[]"
            {if $attribute.class_content.is_multiselect}multiple{/if}>
        {foreach $attribute.class_content.views as $view}
            <option value="{$view.id}"
                    {if $selected_id_array|contains( $view.id )}selected="selected"{/if}>
                {$view.label|wash( xhtml )}
            </option>
        {/foreach}
    </select>
    </p>

    {foreach $attribute.class_content.views as $view}
        {if $view.edit_template}
            {include uri=concat('design:content/datatype/edit/openpachildrenview/', $view.identifier, '.tpl')}
        {/if}
    {/foreach}
{/let}
{/default}
