{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if is_unset( $disabled ) }
    {def $disabled=false()}
{/if}
{if $disabled}
<input class="button-disabled" disabled="disabled" type="submit" name="{$id_name|wash()}" value="{$value|wash()}" />
{else}
<input class="button" type="submit" name="{$id_name|wash()}" value="{$value|wash()}" />
{/if}
{undef $disabled}