{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="warning">

<h2>Errore: accesso negato</h2>
<ul>
    <li>Stai accedendo al servizio da una rete non autorizzata.</li>
</ul>
</div>
