{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let selected_id_array=$attribute.content.options
     extra_configs=$attribute.content.extra_configs}
{section var=Options loop=$attribute.class_content.options}
{section-exclude match=$selected_id_array|contains( $Options.item.id )|not}
    {$Options.item.name|wash( xhtml )}{delimiter}<br/>{/delimiter}
{/section}

<ul>
{foreach $extra_configs as $id => $value}
    <li><strong>{$id}</strong> {$value|wash()}</li>
{/foreach}
</ul>
{/let}

